# -*- coding: utf-8 -*-
"""PrestoCalculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x3cv1EdalTVvjh3Hfc7dYlc5lxRan8Gu
"""

balance = 0 # Read from user
number_of_hours_user_adds = 6 # Read from user
number_of_hours_curr_balance = 0
upload_amount = 0

def print_val(balance, number_of_hours):
  if(balance < 3.10 and balance >=0):
    if(balance == 0):
      temp_val = 0;
    else: 
      temp_val = 3.10 - balance
    number_of_hours_curr_balance = 0
    upload_amount = temp_val + (3.10 * (number_of_hours // 2))
    amount_to_add = upload_amount
    print(f'Amount to Add: {round(amount_to_add, 2)}\n Total balance after adding amount: {round(balance+amount_to_add)}\n Total number of hours: {((amount_to_add+balance)/3.10)*2}\n ')
  else:
    number_of_hours_curr_balance = (balance // 3.10) * 2
    remaining_amount_after_curr_trips = round(balance - (number_of_hours_curr_balance/2 * 3.10), 2)
    amount_to_add = abs(remaining_amount_after_curr_trips - (abs(number_of_hours_user_adds-number_of_hours_curr_balance) // 2) * 3.10)
    print(f'Amount to Add: {round(amount_to_add, 2)}\n Total balance after adding amount: {round(amount_to_add+balance,2)}\n Total number of hours: {((amount_to_add+balance)/3.10)*2}\n ')

    
def main():
  # get_balance()
  print_val(balance, number_of_hours_user_adds)

if __name__ == "__main__":
  main()

